events {
    worker_connections  1024;
}


http {
    server_tokens off;
    charset utf-8;
    
    upstream backend_servers {
    server webappbuild:5174; 
}

    server{
        listen 80 default_server;
        server_name ajileyegeorgeportfolio.com www.ajileyegeorgeportfolio.com;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;
        server_name ajileyegeorgeportfolio.com www.ajileyegeorgeportfolio.com;
        ssl_certificate /etc/letsencrypt/live/ajileyegeorgeportfolio.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/ajileyegeorgeportfolio.com/privkey.pem;
        root /var/www/html;
        index index.html;



        location / {
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_pass http://webappbuild:5174;
        }

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

    }
}