name: Deploy to GCP

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-gcp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          # Use your numeric Project Number here, not the Project ID
          workload_identity_provider: 'projects/440081038764/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'githubserviceaccount@githubauth-495804.iam.gserviceaccount.com'
          token_format: access_token
          access_token_lifetime: 600s
      - name: 'Print Token'
        run: gcloud auth print-access-token
      
      - name: 'Configure Docker'
        run: |
          gcloud auth configure-docker northamerica-northeast2-docker.pkg.dev
      - name: Build and Push Docker Image
        run: |
          docker build -t northamerica-northeast2-docker.pkg.dev/githubauth-495804/mywebrepo/image:tag .
          docker push northamerica-northeast2-docker.pkg.dev/githubauth-495804/mywebrepo/image:tag